### ISSUE TITLE
[Bug] NullPointer when running enrichment script [sf#70]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#15]
**Reported by jenslehmann on 2013-03-07 16:08 UTC**
Running the the enrichment script in SVN with the following parameters results in a NullPointer (and also timeouts):

-e http://live.dbpedia.org/sparql -r http://dbpedia.org/ontology/language --maxExecutionTimeInSeconds 30

 java.lang.NullPointerException
	at org.dllearner.core.owl.ObjectProperty.compareTo(ObjectProperty.java:71)
	at org.dllearner.core.owl.ObjectProperty.compareTo(ObjectProperty.java:1)
	at java.util.TreeMap.put(TreeMap.java:560)
	at java.util.TreeSet.add(TreeSet.java:255)
	at org.dllearner.kb.sparql.SPARQLTasks.getAllObjectProperties(SPARQLTasks.java:685)
	at org.dllearner.algorithms.properties.DisjointObjectPropertyAxiomLearner.start(DisjointObjectPropertyAxiomLearner.java:102)
	at org.dllearner.cli.Enrichment.applyLearningAlgorithm(Enrichment.java:506)
	at org.dllearner.cli.Enrichment.runObjectPropertyAlgorithms(Enrichment.java:382)
	at org.dllearner.cli.Enrichment.start(Enrichment.java:347)
	at org.dllearner.cli.Enrichment.main(Enrichment.java:918)

**Comment by LorenzBuehmann** [comment]
Fixed.
