### ISSUE TITLE
Error executing CLI after release build on develop branch

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#18]
Since several dependencies (e.g. com/davidsoergel/dsutils/1.051/dsutils-1.051, com/davidsoergel/conja/1.061/conja-1.061) were introduced with the SemKernel component that require `com.google.collections:google-collections` calling e.g. `bin/cli` after running the `buildRelease.sh` script will cause the following error:
```
patrick@oklasos:/tmp/dll_trials/dllearner-1.0 $ bin/cli examples/father.conf 
DL-Learner command line interface
Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@7494e528: startup date [Sat Mar 28 18:11:26 CET 2015]; root of context hierarchy
Loading XML bean definitions from URL [jar:file:/tmp/dll_trials/dllearner-1.0/lib/interfaces-1.1-SNAPSHOT.jar!/org/dllearner/configuration/spring/bean-post-processor-configuration.xml]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Platform.systemNanoTime()J
	at com.google.common.base.Ticker$1.read(Ticker.java:60)
	at com.google.common.base.Stopwatch.start(Stopwatch.java:162)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3523)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.semanticweb.owlapi.model.IRI.cache(IRI.java:348)
	at org.semanticweb.owlapi.model.IRI.<init>(IRI.java:369)
	at org.semanticweb.owlapi.model.IRI.create(IRI.java:269)
	at org.semanticweb.owlapi.vocab.OWLRDFVocabulary.<init>(OWLRDFVocabulary.java:356)
	at org.semanticweb.owlapi.vocab.OWLRDFVocabulary.<clinit>(OWLRDFVocabulary.java:62)
	at uk.ac.manchester.cs.owl.owlapi.OWLObjectImpl.<clinit>(OWLObjectImpl.java:87)
	at org.dllearner.core.AbstractCELA.<clinit>(AbstractCELA.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.dllearner.core.AnnComponentManager.<init>(AnnComponentManager.java:117)
	at org.dllearner.core.AnnComponentManager.getInstance(AnnComponentManager.java:142)
	at org.dllearner.confparser3.ConfParserConfiguration.getClass(ConfParserConfiguration.java:76)
	at org.dllearner.configuration.spring.ConfigurationBasedBeanDefinitionRegistryPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationBasedBeanDefinitionRegistryPostProcessor.java:48)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:619)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
	at org.dllearner.configuration.spring.DefaultApplicationContextBuilder.buildApplicationContext(DefaultApplicationContextBuilder.java:60)
	at org.dllearner.cli.CLI.main(CLI.java:259)
``` 
Similar errors were already reported, e.g. [here](http://stackoverflow.com/questions/17690841/gcs-client-library-nosuchmethod-systemnanotime) or [here](https://code.google.com/p/guava-libraries/issues/detail?id=719#c1).

**Comment by patrickwestphal** [comment]
BTW: The exclusion approach proposed [here](http://stackoverflow.com/questions/17690841/gcs-client-library-nosuchmethod-systemnanotime) does not seem to work...
