### ISSUE TITLE
Errors running bin/enrichment

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#49]
Running the enrichment executable on DBpedia live gives me several errors like this one:

```
$ bin/enrichment -e http://live.dbpedia.org/sparql -g http://dbpedia.org -r http://dbpedia.org/ontology/currency
<http://dbpedia.org/ontology/currency> appears to be an object property. Running appropriate algorithms.

Processing property http://dbpedia.org/ontology/currency
Learning of EquivalentObjectProperties axioms ...
Learning 
of EquivalentObjectProperties axioms 
failed.
 ... EquivalentObjectProperties axioms finished
ERROR - An error occurred while generating EquivalentObjectProperties axioms for object property http://dbpedia.org/ontology/currency
java.lang.RuntimeException: Query Execution failed, even with retries.
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry.doTry(QueryExecutionRetry.java:57)
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry.execSelect(QueryExecutionRetry.java:83)
	at org.dllearner.core.AbstractAxiomLearningAlgorithm.executeSelectQuery(AbstractAxiomLearningAlgorithm.java:469)
	at org.dllearner.algorithms.properties.ObjectPropertyHierarchyAxiomLearner.run(ObjectPropertyHierarchyAxiomLearner.java:114)
	at org.dllearner.algorithms.properties.PropertyAxiomLearner.learnAxioms(PropertyAxiomLearner.java:97)
	at org.dllearner.core.AbstractAxiomLearningAlgorithm.start(AbstractAxiomLearningAlgorithm.java:251)
	at org.dllearner.algorithms.properties.MultiPropertyAxiomLearner.applyAlgorithm(MultiPropertyAxiomLearner.java:300)
	at org.dllearner.algorithms.properties.MultiPropertyAxiomLearner.lambda$start$0(MultiPropertyAxiomLearner.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.jena.query.QueryExecException: HTTP QueryExecution has been closed
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry.doTry(QueryExecutionRetry.java:54)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.jena.query.QueryExecException: HTTP QueryExecution has been closed
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:98)
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.execSelect(QueryExecutionCacheEx.java:210)
	at org.aksw.jena_sparql_api.core.QueryExecutionDecoratorBase.execSelect(QueryExecutionDecoratorBase.java:140)
	at org.aksw.jena_sparql_api.delay.core.QueryExecutionDelay.execSelect(QueryExecutionDelay.java:42)
	at org.aksw.jena_sparql_api.core.QueryExecutionDecoratorBase.execSelect(QueryExecutionDecoratorBase.java:140)
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry.access$101(QueryExecutionRetry.java:23)
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry$2.call(QueryExecutionRetry.java:86)
	at org.aksw.jena_sparql_api.retry.core.QueryExecutionRetry$2.call(QueryExecutionRetry.java:83)
	at com.nurkiewicz.asyncretry.AsyncRetryExecutor$2.call(AsyncRetryExecutor.java:72)
	at com.nurkiewicz.asyncretry.SyncRetryJob.run(SyncRetryJob.java:22)
	at com.nurkiewicz.asyncretry.RetryJob.run(RetryJob.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
Caused by: java.lang.RuntimeException: org.apache.jena.query.QueryExecException: HTTP QueryExecution has been closed
	at org.aksw.jena_sparql_api.http.HttpExceptionUtils.makeHumanFriendly(HttpExceptionUtils.java:17)
	at org.aksw.jena_sparql_api.http.QueryExecutionHttpWrapper.wrapException(QueryExecutionHttpWrapper.java:69)
	at org.aksw.jena_sparql_api.http.QueryExecutionHttpWrapper.execSelect(QueryExecutionHttpWrapper.java:26)
	at org.aksw.jena_sparql_api.cache.core.QueryExecutionCacheEx.doCacheResultSet(QueryExecutionCacheEx.java:76)
	... 17 more
Caused by: org.apache.jena.query.QueryExecException: HTTP QueryExecution has been closed
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.checkNotClosed(QueryEngineHTTP.java:534)
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:350)
	at org.aksw.jena_sparql_api.http.QueryExecutionHttpWrapper$1.get(QueryExecutionHttpWrapper.java:29)
	at org.aksw.jena_sparql_api.http.QueryExecutionHttpWrapper$1.get(QueryExecutionHttpWrapper.java:26)
	at org.aksw.jena_sparql_api.http.QueryExecutionHttpWrapper.wrapException(QueryExecutionHttpWrapper.java:55)
	... 19 more
```

**Comment by patrickwestphal** [comment]
This is due to endpoint restrictions and not really a bug.
